### ISSUE TITLE
Malformed comments with formatoptions+=r

### ISSUE THREAD

**Issue by SammysHP** [chrisbra/vim-xml-ftplugin#7]
By default the ftplugin will set `formatoptions+=r`.

Start with a simple XML file like

```xml
<some>
</some>
```

Now start a comment (`|` denotes the cursor):

```xml
<some>
    <!--|
</some>
```

And press <kbd>Return</kbd>

```xml
<some>
    <!--
    --> |
</some>
```

Well, this is not perfect as now you have to delete the extra space and go back inside the comment. Also I didn't ask for auto closing, of course. ;)

But there is even a bigger problem: comment continuation. Same start as above, but start with a comment:

```xml
<some>
    <!--|
    -->
</some>
```

Press <kbd>Return</kbd> and you will get

```xml
<some>
    <!--
    --> |
    -->
</some>
```

Add some text and press <kbd>Return</kbd> again:

```xml
<some>
    <!--
        --> foobar
        |
    -->
</some>
```

Using b93e7bcadcc5b1cfebbc42f4efcc22c0525341fe

**Comment by chrisbra** [comment]
yeah this is confusing. However, I like the current behaviour and it has been like this since I overtook maintenance, so I am not going to change it. If you don't like the effect of `formatoptions+=r`, you can override it using a OptionSet autocommand or using a `after/xml.vim` file. (See `:h ftplugin-overrule`).

**Comment by SammysHP** [comment]
I think the real issue is the generation of

```xml
<!--
-->
-->
```

Using `:setlocal comments=s:<!--,m:\ ,e:-->` fixes the issue for me, but I doesn't understand the issue that is linked in the ftplugin file.
